--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEGUIDORES
--------------------------------------------------------

  CREATE TABLE "HR"."SEGUIDORES" 
   (	"SEGUIDORES_ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DNI" NUMBER, 
	"FECHA_NACIEMIENTO" NUMBER, 
	"SEGUIDORES_PELIGROSOS" NUMBER, 
	"AFICION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEGUIDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SEGUIDORES_PK" ON "HR"."SEGUIDORES" ("SEGUIDORES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SEGUIDORES
--------------------------------------------------------

  ALTER TABLE "HR"."SEGUIDORES" ADD CONSTRAINT "SEGUIDORES_PK" PRIMARY KEY ("SEGUIDORES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SEGUIDORES" MODIFY ("SEGUIDORES_ID" NOT NULL ENABLE);
